fieldLayouts:
  6846db96-7b73-4673-ae71-da5bd2d44bda:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 998222ad-fdb0-4896-a4c9-8e7fcf7c8d76
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9cbd45a0-9f66-474f-956f-c7fee115c35e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 743c097a-2cd8-4553-a10c-e78018f8ba44 # Athletics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a85d31f-78bd-44a1-8382-84a423ffed79
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af9e0f34-c433-40dc-b922-99f9d9a0a282 # Stealth
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27427ff3-2d91-4788-8e8b-d1c0b21a3583
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b44bd82-3a41-4103-ac55-03eafad3d484 # Aiming
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f0b810f-c22c-4b1a-835c-0b32d70b8d01
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b336b04-0ee7-4a60-9b1c-fec46eccc641 # Striking
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 981ae912-ee59-4929-aa41-e2d05eb4dd15
            userCondition: null
            warning: null
            width: 100
        name: 'Prowess Attributes'
        uid: 3361a022-bfef-4b91-86f3-0b553c4b1a0a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5bf4a522-ac48-4ea9-a4e1-8fd2cb06dbce # Lore
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b835a875-3318-466d-a9ad-bcec69677a85
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a0d1a088-be6c-47ca-97ce-c7f332fb5abc # Tinker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0752a40c-441f-49c3-b620-594c545fcfb6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 834ec2e6-0005-4034-a045-0d8a0d24ec94 # Nature
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e675044-d12d-449e-8cba-0d63c2e6f84d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2ed387b-af85-493c-92d5-4124282a0414 # Healing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a79a647b-e5af-4938-b15d-023d6eb9aa77
            userCondition: null
            warning: null
            width: 100
        name: 'Intellect Attributes'
        uid: 1646af61-34d4-4e93-a193-822e42128176
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e4615e4d-f312-4be1-9cf4-aa526c3bb4ca # Insight
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a76c5afd-64c8-4cc4-b46f-0f81b9cd4c4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d8ad8265-f77d-40db-8680-ec0787d4d971 # Perception
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 587a72b8-7887-48d4-a840-dfb7aabd3a9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c9f3ebd-779f-47c3-baba-c579aef22c99 # Communication
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13bb4d10-cb65-4986-b571-11a9ca24296a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2b163d6-f50b-4814-b880-6e28a9d73608 # Performance
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c890aef6-5c48-4ad5-8999-f6574112bd9f
            userCondition: null
            warning: null
            width: 100
        name: 'Cunning Attributes'
        uid: ea465321-dc3e-4424-9107-aa13da9215a4
        userCondition: null
handle: class
hasTitleField: true
name: Class
section: 052d9fea-7f29-4e6e-8348-6aa47c7d8e7c # Classes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
