fieldLayouts:
  a5a67fd7-5b17-42e7-9e4b-15c8258cb9b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 756888ef-8a3d-449c-9f57-f01a44ec7220 # Approved Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0fc7813-efa0-44c5-84d7-b9f8e545161a
            userCondition: null
            warning: null
            width: 100
        name: Admin
        uid: ebfb890a-6d1d-4c1a-a14c-bbc36d736987
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 54e71227-63a7-476e-831a-555ce410deb1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: efc16731-2af7-4e75-b152-d8fe698536c8 # Character Picker
            instructions: null
            label: Attribution
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22d9020a-65cf-4ad9-b3d1-c87ff7fc624c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b1af383-2909-45d1-b416-3419b0311098 # Image 01
            instructions: null
            label: Thumbnail
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fee15c56-2f82-4743-984f-6228ef67f4b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac4ed950-31b5-44f7-b593-097e217af77c # Text Area 01
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 359206cc-f12e-49e7-a0e1-261b9bce929b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0c571c3-dacc-4892-b8a4-d03dbb8cc231 # Entry Picker 01
            instructions: null
            label: 'Associated Hex'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49fe08d4-eb2a-40a8-a60d-f2b994c9ff71
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48f4931b-9d71-4e53-b332-6f2bf43c7299
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b49a84fa-d0e2-4861-9efd-6318d14f5b19 # Fabrications
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
