fieldLayouts:
  04a75d25-769d-49d1-9673-6466b2a097db:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9bea0668-580f-4945-8ba7-33e3f7b89b73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1cd276a1-fc62-4410-b5d4-6c395cdac6b6 # Characters Picker
            instructions: null
            label: 'Discovery Team'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f9dca70-e75e-464f-a254-ab97c168c503
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: baf1be30-d9bd-4b40-8956-5e2b3a4570fd # Landmark Boolean
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efc6e680-3ed4-45dd-a89d-eba8e435ed04
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b1af383-2909-45d1-b416-3419b0311098 # Image 01
            instructions: null
            label: Thumbnail
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa32bea9-60eb-4689-abad-fb8e796f295e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac4ed950-31b5-44f7-b593-097e217af77c # Text Area 01
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14ab9fdd-f25e-48d6-b042-5b6586c3fc51
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0c571c3-dacc-4892-b8a4-d03dbb8cc231 # Entry Picker 01
            instructions: null
            label: 'Associated Hex'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c84fc829-390e-4d68-8548-8a4138a49909
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 113524d6-b539-450a-b3fc-e823afe365bc
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5da5c0cc-6782-47b8-a32e-5e2d9c70161b # Fixtures
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
