fieldLayouts:
  f3aa4729-b36d-41c0-8fb6-bbaac0e9aafc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 913e0e40-caa5-404b-9e5b-09a099eaa3a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac4ed950-31b5-44f7-b593-097e217af77c # Text Area 01
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b7fded5-f67c-46e4-ac28-5945611ce9cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 45bddda1-8437-4a2b-9988-a084252d7a46
        userCondition: null
handle: feat
hasTitleField: true
name: Feat
section: 052d9fea-7f29-4e6e-8348-6aa47c7d8e7c # Classes
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
