fieldLayouts:
  2029aaf8-d987-4014-803a-6ecee62ae3af:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a8fda456-653e-4099-84f9-47e4f46a5494
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac4ed950-31b5-44f7-b593-097e217af77c # Text Area 01
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f5a77ee-e225-4813-ad8c-4261f1ca755e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 131f22d2-fc07-4480-8efa-9aacf7e22f87
        userCondition: null
handle: gameRules
hasTitleField: true
name: Rules
section: a415b1bd-53f0-4e63-9265-fc72c759c4d3 # Game Sytems
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
