tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: c4e4e401-917f-4ac2-80b9-334007bf199a # Game Master Switch
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 0e41d2d6-4b14-4386-a69c-49f936d67e5b
        userCondition: null
        warning: null
        width: 100
    name: 'Game Master'
    uid: 0bceebad-eb04-4a82-bd85-2c2e8d1c8de1
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 485d483c-5435-4217-8ee1-6fe26819ea7c # Grails Picker
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a2ed38ad-d4b1-4c27-948b-62f4393dc5b7
        userCondition: null
        warning: null
        width: 100
    name: Grails
    uid: d185f042-fa56-4fbc-a6f6-762b880bfc85
    userCondition: null
