columnSuffix: phzgerdx
contentColumnType: integer(10)
fieldGroup: 51adbf9d-694c-41e1-8b70-196225cb9ea3 # Common
handle: hexId
instructions: null
name: 'Hex ID'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
