columnSuffix: tvxllatn
contentColumnType: smallint(2)
fieldGroup: 51adbf9d-694c-41e1-8b70-196225cb9ea3 # Common
handle: stress
instructions: null
name: Stress
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: 12
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
