defaultPlacement: end
enableVersioning: true
handle: encounters
name: Encounters
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  48830c8f-d2e4-4358-9a07-e909eb7fa688: # Grailhold
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 0096b101-fd80-474c-8287-36e6640290a7
type: structure
